# Site Information
site_name: test 1012
site_url: https://github.com/kikyoo33/Test.git
# site_description: test 1012

# # Repository Information
# repo_name: Test
# repo_url: https://github.com/kikyoo33/Test.git
# edit_uri: 'edit/main/docs'
docs_dir: 'docs'
# # site_dir: 'site'
# remote_branch: 'gh-pages'
# remote_name: 'origin'

# Server info
# dev_addr: '127.0.0.1:8000'

nav:

  - Table of Content: 

    - 0. Information: index.md

    - 1. Overview: Overview.md

    - 2. Scope: 

      - 2.2 System Context: 

        - 'System Context' : System Context.md

    - 5. Architecture: 

      - 5.1 Architecture Overview: 

        - 5.1.1 Services View: 

          - 'sv' : Services View/aodservices_3C17Ktrkiey.md

      - 5.2 Architectural Decisions: 

        - 'Premises for single-tenant cloud platform' : Architectural Decisions/architecturaldecision_BkeLtsg4mo.md

        - 'A set' : Architectural Decisions/architecturaldecision_BJbLYslVQi.md

        - 'Copy of Premises for single-tenant cloud platform' : Architectural Decisions/architecturaldecision_BkwtigNmo.md

        - 'Copy of A set' : Architectural Decisions/architecturaldecision_HkxwFog4Qj.md

        - 'Copy of Frequency of Data Transfer' : Architectural Decisions/architecturaldecision_S1-PKoeVmo.md

        - 'Copy of Data Veracity' : Architectural Decisions/architecturaldecision_SyNDYseVmj.md

        - 'Frequency of Data Transfer' : Architectural Decisions/architecturaldecision_SkfUYoe4ms.md

        - 'Data Veracity' : Architectural Decisions/architecturaldecision_SJrUYoxNmj.md

      - 5.3 Component Model: 

        - 5.3.1 Static View: 

          - 'stv' : Static View/cmstaticview_3C182KZKvJi.md

    - 8. RACI: 

      - 'a' : RACI/notes_rygJvzeHQj.md


   
       


markdown_extensions:

  - md_in_html

  - toc:

      permalink: True

  - footnotes

  - tables

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list

theme:

  name: material
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  logo: assets/ca.svg
  favicon: assets/ca.svg 
  features:
    # - navigation.tabs
    - navigation.tabs.sticky
  custom_dir:
    theme

extra_css:
  - extra.css
extra_javascript:
  - extra.js