# Site Information
site_name: test gitpagew 0926
site_url: https://github.com/kikyoo33/Test.git
# site_description: test gitpagew 0926

# # Repository Information
# repo_name: Test
# repo_url: https://github.com/kikyoo33/Test.git
# edit_uri: 'edit/main/docs'
docs_dir: 'docs'
# # site_dir: 'site'
# remote_branch: 'gh-pages'
# remote_name: 'origin'

# Server info
# dev_addr: '127.0.0.1:8000'

nav:

  - Table of Content: 

    - 0. Information: index.md

    - 1. Overview: Overview.md

    - 5. Architecture: 

      - 5.1 Architecture Overview: 

        - 5.1.1 Services View: 

          - 'sv2' : Services View/aodservices_3AHlYld1Gp1_HyGR9FWMi.md


   
       


markdown_extensions:

  - md_in_html

  - toc:

      permalink: True

  - footnotes

  - tables

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list

theme:

  name: material
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  logo: assets/ca.svg
  favicon: assets/ca.svg 
  features:
    # - navigation.tabs
    - navigation.tabs.sticky
  custom_dir:
    theme

extra_css:
  - extra.css
extra_javascript:
  - extra.js