# Site Information
site_name: teamsd 1018
site_url: https://github.com/kikyoo33/Test.git
# site_description: teamsd 1018

# # Repository Information
# repo_name: Test
# repo_url: https://github.com/kikyoo33/Test.git
# edit_uri: 'edit/main/docs'
docs_dir: 'docs'
# # site_dir: 'site'
# remote_branch: 'gh-pages'
# remote_name: 'origin'

# Server info
# dev_addr: '127.0.0.1:8000'

nav:

  - Table of Content: 

    - 0. Information: index.md

    - 1. Overview: Overview.md

    - 2. Persona: 

      - 'persona11' : Misc Diagram/miscdiagram_3CyTkaVnDn4.md

      - 'persona12' : Misc Diagram/miscdiagram_SJiwP9iXj.md

    - 4. Requirements: 

      - 4.1 Functional Requirements (req matrix): 

        - 'FR Name' : Functional Requirements/functionalrequirement_S1Q9P9oQs.md

        - 'FR Name1' : Functional Requirements/functionalrequirement_HJemqPci7s.md

      - 4.2 NFRs: 

        - 'nfr1' : Non Functional Requirements/nonfunctionalrequirement_BJlqiP5sQi.md

        - 'nfr2' : Non Functional Requirements/nonfunctionalrequirement_SJc0D9iXs.md

    - 7. Viability Assessment (RAID): 

      - 7.1 Risks: 

        - 'risks' : Risks/risk_rygP7_9oQj.md

    - 8. Misc Diagram: 

      - 'misc2' : Misc Diagram/miscdiagram_3CyU19Xxx1L.md


   
       


markdown_extensions:

  - md_in_html

  - toc:

      permalink: True

  - footnotes

  - tables

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list

theme:

  name: material
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  logo: assets/ca.svg
  favicon: assets/ca.svg 
  features:
    # - navigation.tabs
    - navigation.tabs.sticky
  custom_dir:
    theme

extra_css:
  - extra.css
extra_javascript:
  - extra.js